apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1m
  chart:
    spec:
      chart: authentik
      version: "2023.10.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 1m
  values:
    authentik:
      postgresql:
        host: baywatch-do-4908.postgresql.a.osc-fr1.scalingo-dbs.com
        port: 31418
        name: baywatch_do_4908
        user: baywatch_do_4908
      redis:
        host: redis.authentik.svc.cluster.local.
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - host: id.laplagedigitale.fr
          paths:
            - path: "/"
              pathType: Prefix

  valuesFrom:
    - kind: Secret
      name: env
      valuesKey: DATABASE_PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: env
      valuesKey: SECRET_KEY
      targetPath: authentik.secret_key
