apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1m
  chart:
    spec:
      chart: authentik
      version: "2024.6.0"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 1m
  values:
    global:
      env:
        - name: AUTHENTIK_EMAIL__HOST
          value: smtp-relay.brevo.com
        - name: AUTHENTIK_EMAIL__PORT
          value: "587"
        - name: AUTHENTIK_EMAIL__USERNAME
          value: "baywatch@chobert.fr"
        - name: AUTHENTIK_EMAIL__USE_TLS
          value: "true"
        - name: AUTHENTIK_EMAIL__FROM
          value: "noreply@laplagedigitale.fr"
        - name: AUTHENTIK_EMAIL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: env
              key: BREVO_SMTP_PASSWORD
    authentik:
      postgresql:
        host: baywatch-do-4908.postgresql.a.osc-fr1.scalingo-dbs.com
        port: 31418
        name: baywatch_do_4908
        user: baywatch_do_4908
      redis:
        host: redis.authentik.svc.cluster.local.
      email:
        from: noreply@laplagedigitale.fr
        host: smtp-relay.brevo.com
        port: 587
        username: baywatch@chobert.fr
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - host: id.laplagedigitale.fr
          paths:
            - path: "/"
              pathType: Prefix

  valuesFrom:
    - kind: Secret
      name: env # TODO
      valuesKey: DATABASE_PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: env # TODO
      valuesKey: SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: env # TODO
      valuesKey: EMAIL_PASSWORD
      targetPath: authentik.email.password
