apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1m
  chart:
    spec:
      chart: authentik
      version: "2023.10.7"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 1m
  values:
    env:
      AUTHENTIK_EMAIL__HOST: smtp-relay.brevo.com
      AUTHENTIK_EMAIL__PORT: "587"
      AUTHENTIK_EMAIL__USERNAME: "baywatch@chobert.fr"
      AUTHENTIK_EMAIL__USE_TLS: "true"
      AUTHENTIK_EMAIL__FROM: "noreply@laplagedigitale.fr"
    authentik:
      postgresql:
        host: baywatch-do-4908.postgresql.a.osc-fr1.scalingo-dbs.com
        port: 31418
        name: baywatch_do_4908
        user: baywatch_do_4908
      redis:
        host: redis.authentik.svc.cluster.local.
      email:
        from: noreply@laplagedigitale.fr
        host: smtp-relay.brevo.com
        port: 587
        username: baywatch@chobert.fr
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - host: id.laplagedigitale.fr
          paths:
            - path: "/"
              pathType: Prefix

  valuesFrom:
    - kind: Secret
      name: env # TODO
      valuesKey: DATABASE_PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: env # TODO
      valuesKey: SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: env # TODO
      valuesKey: EMAIL_PASSWORD
      targetPath: authentik.email.password
    - kind: Secret
      name: env # TODO
      valuesKey: BREVO_SMTP_PASSWORD
      targetPath: env.AUTHENTIK_EMAIL__PASSWORD
