apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: authentik

resources:
  - helm-repository.yaml
  - helm-release.yaml

configMapGenerator:
  - name: scalingo-db-ca-cert
    files:
      - ca.pem

secretGenerator:
  - name: env
    envs:
      - .env

configurations:
  - kustomizeconfig.yaml
