---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/laplagedigitale/baywatch

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
