apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: baserow
spec:
  chart:
    spec:
      chart: baserow
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: christianknell
        namespace: baserow
      version: 1.27.0
  interval: 1m
  values:
    backend:
      ingress:
        enabled: true
        hostname: tables.laplagedigitale.fr
        paths:
          asgiPath: /ws/
          wsgiPath: /api/
    config:
      publicBackendUrl: https://tables.laplagedigitale.fr/
      publicFrontendUrl: https://tables.laplagedigitale.fr/
    frontend:
      ingress:
        enabled: true
        hostname: tables.laplagedigitale.fr
    postgresql:
      enabled: true
    redis:
      enabled: true
