apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baserow
spec:
  chart:
    spec:
      chart: baserow
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: christianknell
        namespace: baserow
      version: 1.27.0
  interval: 1m
  values:
    backend:
      asgi:
        image:
          tag: "1.22.2"
      wsgi:
        image:
          tag: "1.22.2"
      celery:
        image:
          tag: "1.22.2"
      ingress:
        enabled: true
        hostname: tables.laplagedigitale.fr
        paths:
          asgiPath: /ws/
          wsgiPath: /api/

    frontend:
      image:
        tag: "1.22.2"
      ingress:
        enabled: true
        hostname: tables.laplagedigitale.fr

    config:
      publicBackendUrl: https://tables.laplagedigitale.fr
      publicFrontendUrl: https://tables.laplagedigitale.fr
    postgresql:
      enabled: true
    redis:
      enabled: true
