apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

commonLabels:
  app.kubernetes.io/name: n8n

resources:
  - ./namespace.yaml
  - ./service.yaml
  - ./statefulset.yaml
  - ./ingress.yaml
