apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik/authentik
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 1m
  values:
    authentik:
      postgresql:
        host: baywatch-do-4908.postgresql.a.osc-fr1.scalingo-dbs.com
        port: 31418
        name: baywatch_do_4908
        user: baywatch_do_4908
  valuesFrom:
    - kind: Secret
      name: db-password
      valuesKey: DATABASE_PASSWORD
      targetPath: authentik.postgresql.password
