apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

commonLabels:
  app.kubernetes.io/name: authentik

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

configMapGenerator:
  - name: scalingo-db-ca-cert
    files:
      - values.yaml
      - ca.pem

secretGenerator:
  - name: db-url
    envs:
      - .env
