apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: env
  namespace: authentik
data:
  DATABASE_PASSWORD: NE1lSzFHVzhmajd0RE1mbW0zTHo=
  SECRET_KEY: RVhWUEF0ajkxN0xRZzdaN3FNZldVV0FCNTE5aGlkeGhXUDlMaUpPYnduSzNFZ1FMeGw=
  EMAIL_PASSWORD: eHNtdHBzaWItMWE5YTdlY2I3YjA5Zjc3ODBiYmZkYjA4YzdkNDc4MjVmM2I3ODliZTY2ZGJkOTExOWJkN2ZhZmExZjhhODI1My1yNEFNa0lQeW5TUktXNWRqCg==
