apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  template:
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2022.3.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
              readOnly: true

      volumes:
        - name: config
          projected:
            - secret:
                secretName: tunnel-credentials
              items:
                - key: credentials.json
                  path: credentials.json
            - configMap:
                name: cloudflared
              items:
                - key: config.yaml
                  path: config.yaml
