apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

commonLabels:
  app.kubernetes.io/name: cloudflared

resources:
  - namespace.yaml
  - deployment.yaml

configMapGenerator:
  - name: cloudflared
    files:
      - ./config.yaml
