apiVersion: apps/v1
kind: Deployment
metadata:
  name: logto
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: logto
          image: ghcr.io/logto-io/logto
          env:
            - name: PORT
              value: "3001"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
          ports:
            - containerPort: 3001
              name: http
