apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- https://github.com/kubernetes/ingress-nginx//deploy/static/provider/baremetal/?ref=controller-v1.9.3

patches:
- path: service-patch.yaml
  target:
    kind: Service
- path: ingress-class-patch.yaml
  target:
    kind: IngressClass
- path: configmap.yaml
  target:
    kind: ConfigMap
  
